<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;

    protected $fillable = [
        'background_image_cover',
        'background_image_menu',
        'background_image_cocktails',
        'background_image_wines',
        'logo',
        'text_color_cover',
        'text_color_cover_secondary',
        'cover_hero_kicker',
        'cover_hero_title',
        'cover_hero_paragraph',
        'cover_location_text',
        'cover_highlight_1_label',
        'cover_highlight_1_title',
        'cover_highlight_1_description',
        'cover_highlight_2_label',
        'cover_highlight_2_title',
        'cover_highlight_2_description',
        'cover_highlight_3_label',
        'cover_highlight_3_title',
        'cover_highlight_3_description',
        'cover_cta_menu_bg_color',
        'cover_cta_menu_text_color',
        'cover_cta_cafe_bg_color',
        'cover_cta_cafe_text_color',
        'cover_cta_cocktails_bg_color',
        'cover_cta_cocktails_text_color',
        'cover_cta_events_bg_color',
        'cover_cta_events_text_color',
        'cover_cta_reservations_bg_color',
        'cover_cta_reservations_text_color',
        'cover_cta_vip_bg_color',
        'cover_cta_vip_text_color',
        'show_cta_menu',
        'show_cta_cafe',
        'show_cta_cocktails',
        'show_cta_events',
        'show_cta_reservations',
        'show_cta_vip',
        'featured_card_bg_color',
        'featured_card_text_color',
        'featured_tab_bg_color',
        'featured_tab_text_color',
        'text_color_menu',
        'text_color_cocktails',
        'text_color_wines',
        'card_opacity_cover',
        'card_bg_color_cover',
        'card_opacity_menu',
        'card_opacity_cocktails',
        'card_opacity_wines',
        'font_family_cover',
        'font_family_menu',
        'font_family_cocktails',
        'font_family_wines',
        'button_color_cover',
        'button_color_menu',
        'button_color_cocktails',
        'button_color_wines',
        'category_name_bg_color_menu',
        'category_name_text_color_menu',
        'category_name_font_size_menu',
        'subcategory_name_bg_color_menu',
        'subcategory_name_text_color_menu',
        'category_name_bg_color_cocktails',
        'category_name_text_color_cocktails',
        'category_name_font_size_cocktails',
        'subcategory_name_bg_color_cocktails',
        'subcategory_name_text_color_cocktails',
        'category_name_bg_color_wines',
        'category_name_text_color_wines',
        'category_name_font_size_wines',
        'subcategory_name_bg_color_wines',
        'subcategory_name_text_color_wines',
        'card_bg_color_menu',
        'card_bg_color_cocktails',
        'card_bg_color_wines',
        'facebook_url',
        'twitter_url',
        'instagram_url',
        'phone_number',
        'business_hours',
        'button_font_size_cover',
        'fixed_bottom_font_size',
        'fixed_bottom_font_color',
        'button_label_menu',
        'button_label_cocktails',
        'button_label_wines',
        'button_label_events',
        'button_label_vip',
        'button_label_reservations',
        'cover_gallery_image_1',
        'cover_gallery_image_2',
        'cover_gallery_image_3',
        'menu_hero_image',
        'cocktail_hero_image',
        'coffee_hero_image',
        'cta_image_menu',
        'cta_image_cafe',
        'cta_image_cocktails',
        'cta_image_events',
        'cta_image_reservations',
        'loyalty_points_per_visit',
        'loyalty_terms',
        'loyalty_email_copy',
        'tab_label_menu',
        'tab_label_cocktails',
        'tab_label_wines',
        'tab_label_events',
        'tab_label_loyalty',
        'show_tab_menu',
        'show_tab_cocktails',
        'show_tab_wines',
        'show_tab_events',
        'show_tab_campaigns',
        'show_tab_popups',
        'show_tab_loyalty',
        'tip_presets',
        'tip_allow_custom',
        'tip_allow_skip',
    ];

    protected $casts = [
        'show_tab_menu' => 'boolean',
        'show_tab_cocktails' => 'boolean',
        'show_tab_wines' => 'boolean',
        'show_tab_events' => 'boolean',
        'show_tab_campaigns' => 'boolean',
        'show_tab_popups' => 'boolean',
        'show_tab_loyalty' => 'boolean',
        'show_cta_menu' => 'boolean',
        'show_cta_cafe' => 'boolean',
        'show_cta_cocktails' => 'boolean',
        'show_cta_events' => 'boolean',
        'show_cta_reservations' => 'boolean',
        'show_cta_vip' => 'boolean',
        'tip_presets' => 'array',
        'tip_allow_custom' => 'boolean',
        'tip_allow_skip' => 'boolean',
    ];
}
